In [23]:
import numpy as np
import json
import utils

In [2]:
json_file = '../data/11HB6XZSh1Q/pano/points/point_003869070b5641efb8a71b8a0245aae2.json'

In [3]:
csv_file = '../data/11HB6XZSh1Q/sweep_locations.csv'

In [20]:
for line in open(csv_file):
    ls =line.split(' ')
    if ls[0] == '003869070b5641efb8a71b8a0245aae2':
        pose_csv = np.array(ls[1:8]).astype(np.float32)

In [11]:
pose_dict = json.load(open(json_file))

In [41]:
p = np.concatenate(np.array(pose_dict[0][u'camera_rt_matrix'] + [[0,0,0,1]])).astype(np.float32).reshape((4,4))
#rotation = np.array([[0,-1,0,0],[-1,0,0,0],[0,0,1,0],[0,0,0,1]])
#p = np.dot(rotation, p)

In [42]:
p

array([[  9.49621797e-01,   3.13134640e-01,   1.28523270e-02,
          1.88963938e+00],
       [ -3.13175946e-01,   9.49694276e-01,   1.28583587e-03,
         -4.20118427e+00],
       [ -1.18031418e-02,  -5.24609722e-03,   9.99916553e-01,
         -4.28687191e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00]], dtype=float32)

In [55]:
trans = pose_csv[:3]
quat = pose_csv[3:]
rot = utils.to_r(quat)
print trans
print rot

[-3.1607511   3.37563992  4.2676301 ]
[[-0.99991715 -0.0052462  -0.01180312]
 [-0.00128594  0.94969475 -0.31317616]
 [ 0.01285234 -0.31313485 -0.94962227]]


In [60]:
-np.dot(p[:3, :3].T, p[:3, -1])

array([-3.16075134,  3.37563992,  4.2676301 ], dtype=float32)

In [124]:
rotation = np.array([[0,0,-1],[0,-1,0],[1,0,0]])

In [127]:
np.dot(np.dot(rotation, p[:3, :3]), rotation)

array([[-0.99991655, -0.0052461 , -0.01180314],
       [-0.00128584,  0.94969428, -0.31317595],
       [ 0.01285233, -0.31313464, -0.9496218 ]])

In [128]:
rot

array([[-0.99991715, -0.0052462 , -0.01180312],
       [-0.00128594,  0.94969475, -0.31317616],
       [ 0.01285234, -0.31313485, -0.94962227]], dtype=float32)